# Generated by Django 5.0.6 on 2024-06-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_id', models.IntegerField()),
                ('stage', models.CharField(choices=[('male', 'Init'), ('female', 'Doing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], max_length=32)),
                ('score', models.IntegerField()),
                ('created', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'M'), ('female', 'F')], max_length=32)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('credit', models.IntegerField()),
                ('score', models.IntegerField()),
                ('level', models.IntegerField()),
                ('created', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
